### PR TITLE
Added a new JsonRecordSetIterator and Writer

### PR DESCRIPTION
**Pull request by brenthale**
I renamed 'RecordSetIterator' to 'XmlRecordSetIterator' and created an Interface across it and the new JsonRecordSetIterator.  

Dang...I did 'git' wrong.   Don't merge this one in.  It wasn't supposed to include the changes for a new Event type of 'Court'.

### CODE REVIEW

**Comment by stoicflame** [comment]
Hey, @brenthale, thanks for the PR, but it looks like your local clone still had all the commits from #21. Will you rebase and include just the last three commits so we can merge?

**Comment by brenthale** [comment]
Sorry about my misuse of Git.  I did figure out how to revert the commits that were originally for the addition of the new Event type of 'Court'.  I didn't intend to do it on the same branch.  I guess I need a new Fork off of master when I do this.

Anyway...This Pull Request is for the addition of a JsonRecordSetIterator.  Robokey'ing was hoping to give us files to be ingested in Json format.  The previous RecordSetIterator was locked into XML.  The new code made RecordSetIterator an Interface and renamed the previous RecordSetIterator as XmlRecordSetIterator.  

Since RecordSetIterator is now an Interface this will break existing code instantiating a RecordSetIterator.  I feel like the new naming convention is more sound than any alternative I could think of.

I thought of adding a Factory class but after playing with it figured it was a little overkill.

Let me know what you think.
Brent

**Comment by stoicflame** [comment]
I just went ahead and did an [interactive rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i), keeping only the three commits relevant to this pull request.

**Comment by brenthale** [comment]
Thanks...can we get a release build so we can use it.

**Comment by stoicflame** [comment]
1.0.127.M1 is building [here](https://gedcom.ci.cloudbees.com/job/gedcomx-java-release/160/).

**Pull request closed without merging**
